package com.yourssu.ragent.ui.chat.reference

import android.annotation.SuppressLint
import android.util.LruCache
import android.webkit.JavascriptInterface
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.ContentCopy
import androidx.compose.material.icons.outlined.ErrorOutline
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.compose.ui.res.stringResource
import com.yourssu.ragent.R
import com.yourssu.ragent.ui.chat.reference.theme.AgentTheme

/**
 * [Performance optimization - render result caching]
 * Problem: Each code/Mermaid block has a WebView. When scrolling away and back,
 *          a new WebView was created and highlight.js/mermaid.js ran every time.
 *          (Parsing and running JS takes tens to hundreds of ms per block, causing frame drops.)
 * Solution: Store "completed render results" in an in-memory LRU cache keyed by content hash,
 *           then inject cached results into HTML without running JS when rendering the same code.
 *
 * Cache key design:
 *   "${code.hashCode()}/$dark" ??code content + dark mode state.
 *   Dark mode uses different highlight (github/github-dark) and Mermaid themes, so keys are separate.
 *
 * LRU (24 entries): Keeps only recently viewed blocks. Older entries are removed automatically
 *   to prevent unbounded memory growth. Because this is process memory, each block renders once again after restart.
 */
object CodeRenderCache {
    private const val MAX_ENTRIES = 24

    // key: "${code.hashCode()}/$dark" ??highlighted "span fragments" generated by hljs
    // (The <code> element's innerHTML. Do not store the <code>/<pre> shells because
    // the cache-hit template wraps the content in a normalized structure when reused.)
    val highlightedHtml = LruCache<String, String>(MAX_ENTRIES)

    // key: "${code.hashCode()}/$dark" ??SVG string generated by mermaid.render()
    val mermaidSvg = LruCache<String, String>(MAX_ENTRIES)

    fun codeKey(code: String, dark: Boolean, language: String = ""): String =
        "${code.hashCode()}/$dark/$language"
}

@Composable
fun CodeWebView(
    code: String,
    declaredLanguage: String = "",
    mermaid: Boolean,
    renderKey: Int = 0,
    onAskAi: (String) -> Unit = {}
) {
    val normalizedCode = remember(code) { normalizeResourceIndentation(code) }
    val language = remember(normalizedCode, declaredLanguage) {
        declaredLanguage
            .trim()
            .lowercase()
            .takeIf { it.isNotEmpty() }
            ?.let { if (it == "text") "plaintext" else it }
            ?: detectLanguage(normalizedCode)
    }
    val colors = AgentTheme.colors
    val context = LocalContext.current
    val backgroundColor = colors.codeBackground
    val backgroundHex = colors.codeBackgroundHex
    val highlightStyle = if (colors.isDark) "github-dark" else "github"
    val mermaidTheme = if (colors.isDark) "dark" else "default"
    val errorColorHex = colors.mermaidErrorHex
    val renderToken = listOf(normalizedCode, language, mermaid, colors.isDark, renderKey).hashCode()
    val activeRenderToken = rememberUpdatedState(renderToken)
    // [Cache safety] JS bridge callbacks are asynchronous, so the response may belong to an older WebView
    // because the code has already changed (for example, during streaming).
    // Use rememberUpdatedState to always reference the latest key and prevent stale results
    // from being cached under the wrong key. (Same pattern as activeRenderToken.)
    val activeCacheKey = rememberUpdatedState(
        CodeRenderCache.codeKey(normalizedCode, colors.isDark, language)
    )
    // Preserve the error message when switching from the code view to the Mermaid view during streaming.
    var mermaidError by remember(normalizedCode) { mutableStateOf<String?>(null) }
    var showMermaidErrorDialog by remember { mutableStateOf(false) }
    val height = remember(normalizedCode, mermaid) {
        mutableStateOf(
            if (mermaid) 300.dp
            else (normalizedCode.lines().size * 20 + 27).coerceAtLeast(50).dp   // Code area height (adjustment +27)
        )
    }

    val html = remember(normalizedCode, language, mermaid, colors.isDark, renderKey) {
        val cacheKey = CodeRenderCache.codeKey(normalizedCode, colors.isDark, language)
        if (mermaid) {
            val escapedCode = normalizedCode
                .replace("\\", "\\\\")
                .replace("`", "\\`")
                .replace("${'$'}", "\\${'$'}")

            val cachedSvg = CodeRenderCache.mermaidSvg.get(cacheKey)

            if (cachedSvg != null) {
                // [Performance optimization - cache-hit path]
                // The SVG generated by mermaid.render() is already available, so do not include
                // the mermaid.js <script> tag: 0 ms for JS download, parsing, or execution.
                // Insert the SVG statically into #diagram and only synchronize height (ResizeObserver).
                """
                <!DOCTYPE html>
                <html>
                <head>
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <style>
                        body {
                            margin: 0;
                            padding: 16px;
                            background: $backgroundHex;
                            overflow: visible;
                            box-sizing: border-box;
                        }
                        #diagram {
                            width: 100%;
                            text-align: center;
                        }
                        #diagram svg {
                            display: block;
                            width: 100%;
                            height: auto;
                            overflow: visible;
                        }
                    </style>
                </head>
                <body>
                    <div id="diagram">$cachedSvg</div>
                    <script>
                        const diagram = document.getElementById('diagram');
                        const reportHeight = () => {
                            const bodyStyle = window.getComputedStyle(document.body);
                            const verticalPadding = parseFloat(bodyStyle.paddingTop) + parseFloat(bodyStyle.paddingBottom);
                            const height = Math.ceil(diagram.getBoundingClientRect().height + verticalPadding);
                            if (window.Android) window.Android.onDiagramRendered($renderToken, height);
                        };
                        new ResizeObserver(reportHeight).observe(diagram);
                        requestAnimationFrame(reportHeight);
                        setTimeout(reportHeight, 100);
                        setTimeout(reportHeight, 300);
                        setTimeout(reportHeight, 700);
                        if (document.fonts?.ready) document.fonts.ready.then(reportHeight);
                    </script>
                </body>
                </html>
                """.trimIndent()
            } else {
                // [Cache-miss path]
                // Load mermaid.min.js from the CDN.
                // On success, send the SVG to Kotlin through the onDiagramSvg bridge for reuse.
                """
                <!DOCTYPE html>
                <html>
                <head>
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <script src="https://cdn.jsdelivr.net/npm/mermaid@10.9.1/dist/mermaid.min.js"></script>
                    <style>
                        body {
                            margin: 0;
                            padding: 16px;
                            background: $backgroundHex;
                            overflow: visible;
                            box-sizing: border-box;
                        }
                        #diagram {
                            width: 100%;
                            text-align: center;
                        }
                        #diagram svg {
                            display: block;
                            width: 100%;
                            height: auto;
                            overflow: visible;
                        }
                        .error {
                            color: $errorColorHex;
                            padding: 10px;
                            font-family: monospace;
                        }
                    </style>
                </head>
                <body>
                    <div id="diagram"></div>
                    <script>
                        const mermaidCode = `__CODE__`;

                        mermaid.initialize({
                            startOnLoad: true,
                            theme: '$mermaidTheme',
                            securityLevel: 'loose',
                            themeVariables: {
                                'fontSize': '14px',
                                'fontFamily': 'sans-serif'
                            }
                        });

                        async function renderMermaid() {
                            try {
                                const { svg } = await mermaid.render('mermaid-diagram', mermaidCode);
                                document.getElementById('diagram').innerHTML = svg;
                                if (window.Android) window.Android.onDiagramSvg($renderToken, svg);
                                if (window.Android) window.Android.onMermaidError($renderToken, '');

                                if (window.Android) {
                                    const reportHeight = () => {
                                        const diagram = document.getElementById('diagram');
                                        const bodyStyle = window.getComputedStyle(document.body);
                                        const verticalPadding = parseFloat(bodyStyle.paddingTop) + parseFloat(bodyStyle.paddingBottom);
                                        const height = Math.ceil(diagram.getBoundingClientRect().height + verticalPadding);
                                        window.Android.onDiagramRendered($renderToken, height);
                                    };
                                    new ResizeObserver(reportHeight).observe(document.getElementById('diagram'));
                                    requestAnimationFrame(reportHeight);
                                    setTimeout(reportHeight, 100);
                                    setTimeout(reportHeight, 300);
                                    setTimeout(reportHeight, 700);
                                    if (document.fonts?.ready) document.fonts.ready.then(reportHeight);
                                }
                            } catch (error) {
                                console.error('Mermaid error:', error);
                                if (window.Android) window.Android.onMermaidError($renderToken, String(error?.message || error));
                                document.getElementById('diagram').innerHTML =
                                    '<div class="error">Mermaid Error: ' + error.message + '</div>';
                            }
                        }

                        renderMermaid();
                    </script>
                </body>
                </html>
                """.trimIndent().replace("__CODE__", escapedCode)
            }
        } else {
            // Code highlighting
            val cachedHighlighted = CodeRenderCache.highlightedHtml.get(cacheKey)

            if (cachedHighlighted != null) {
                // [Performance optimization - cache-hit path]
                // Highlighted HTML (<span> markup) from hljs is already available, so do not include
                // the highlight.min.js <script> tag: 0 ms of JS execution.
                // Loading only the CSS preserves the span class colors.
                """
                <!DOCTYPE html>
                <html>
                <head>
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/$highlightStyle.min.css">
                    <style>
                        body {
                            margin: 0;
                            padding: 0px;
                            background: $backgroundHex;
                            overflow-x: auto;
                            overflow-y: hidden;
                        }
                        ::-webkit-scrollbar { width: 0; height: 3.5px; }  // Scrollbar height
                        ::-webkit-scrollbar-track { background: transparent; }
                        ::-webkit-scrollbar-thumb { background: #808890; border-radius: 5px; }
                        pre {
                            margin: 0;
                            padding: 0px;
                            background: $backgroundHex;
                            border-radius: 6px;
                            overflow-x: auto;
                            white-space: pre;
                        }
                        code {
                            font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
                            font-size: 13px;
                            line-height: 1.5;
                        }
                        .hljs {
                            background: transparent !important;
                        }
                    </style>
                </head>
                <body>
                    <pre><code class="language-${language} hljs">__CODE__</code></pre>
                </body>
                </html>
                """.trimIndent().replace("__CODE__", cachedHighlighted)
            } else {
                // [Cache-miss path]
                // Load highlight.js/CSS from the CDN.
                // [Cache storage condition] Add the callback only when renderKey != 0 (after streaming ends),
                //   and store results only after window load and verifying the global hljs object.
                //   This ensures that a "broken render" is never cached.
                val shouldCache = renderKey != 0
                """
                <!DOCTYPE html>
                <html>
                <head>
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/$highlightStyle.min.css">
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
                    <style>
                        body {
                            margin: 0;
                            padding: 0px;
                            background: $backgroundHex;
                            overflow-x: auto;
                            overflow-y: hidden;
                        }
                        ::-webkit-scrollbar { width: 0; height: 3.5px; }  // Scrollbar height
                        ::-webkit-scrollbar-track { background: transparent; }
                        ::-webkit-scrollbar-thumb { background: #808890; border-radius: 5px; }
                        pre {
                            margin: 0;
                            padding: 0px;
                            background: $backgroundHex;
                            border-radius: 6px;
                            overflow-x: auto;
                            white-space: pre;
                        }
                        code {
                            font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
                            font-size: 13px;
                            line-height: 1.5;
                        }
                        .hljs {
                            background: transparent !important;
                        }
                    </style>
                </head>
                <body>
                    <pre><code class="language-${language}">__CODE__</code></pre>
                    <script>
                        // Run highlighting and capture only after the hljs script has fully loaded.
                        // (The inline script runs immediately after body parsing, so the load event is needed to wait for the external script.)
                        function doHighlight() {
                            try {
                                if (!window.hljs) return; // Give up highlighting and caching if the script fails to load (prevents broken results from being stored).
                                hljs.highlightAll();
                                // [Cache storage rules]
                                // - Store only the code element's "inner span fragments" (excluding the <pre>/<code> shells).
                                // - $shouldCache: do not store while streaming (renderKey == 0).
                                if (window.Android && $shouldCache) {
                                    window.Android.onCodeHighlighted($renderToken, document.getElementsByTagName('code')[0].innerHTML);
                                }
                            } catch (e) {
                                console.error('highlight failed:', e);
                            }
                        }
                        if (document.readyState === 'complete') doHighlight();
                        else window.addEventListener('load', doHighlight);
                    </script>
                </body>
                </html>
                """.trimIndent().replace("__CODE__", escapeHtml(normalizedCode))
            }
        }
    }

    Box(
        modifier = Modifier
            .fillMaxWidth()
            .height(height.value)
            .clip(RoundedCornerShape(20.dp))
            .background(backgroundColor)
    ) {
        key(mermaid, renderKey) {
            AndroidView(
                modifier = Modifier.fillMaxSize(),
                factory = { ctx ->
                    WebView(ctx).apply {
                        setBackgroundColor(android.graphics.Color.TRANSPARENT)
                        isHorizontalScrollBarEnabled = true
                        isVerticalScrollBarEnabled = false
                        isScrollbarFadingEnabled = false
                        scrollBarStyle = android.view.View.SCROLLBARS_INSIDE_OVERLAY
                        settings.apply {
                            javaScriptEnabled = true
                            domStorageEnabled = true
                            allowFileAccess = true
                        }

                        // Add the JavaScript interface
                        addJavascriptInterface(object {
                            @JavascriptInterface
                            fun onDiagramRendered(token: Int, newHeight: Int) {
                                android.os.Handler(android.os.Looper.getMainLooper()).post {
                                    if (token == activeRenderToken.value) {
                                        val newDpHeight = newHeight.dp + 12.dp
                                        height.value = newDpHeight.coerceAtLeast(50.dp)
                                    }
                                }
                            }

                            @JavascriptInterface
                            fun onMermaidError(token: Int, message: String) {
                                android.os.Handler(android.os.Looper.getMainLooper()).post {
                                    if (token == activeRenderToken.value) {
                                        mermaidError = message.takeIf { it.isNotBlank() }
                                    }
                                }
                            }

                            @JavascriptInterface
                            fun onDiagramSvg(token: Int, svg: String) {
                                android.os.Handler(android.os.Looper.getMainLooper()).post {
                                    // [Performance optimization] Store the Mermaid render result SVG in the cache.
                                    // Discard "late responses from an older WebView" by checking the token.
                                    if (token == activeRenderToken.value && svg.isNotBlank()) {
                                        CodeRenderCache.mermaidSvg.put(activeCacheKey.value, svg)
                                    }
                                }
                            }

                            @JavascriptInterface
                            fun onCodeHighlighted(token: Int, html: String) {
                                android.os.Handler(android.os.Looper.getMainLooper()).post {
                                    // [Performance optimization] Store the hljs highlighting result HTML in the cache.
                                    if (token == activeRenderToken.value && html.isNotBlank()) {
                                        CodeRenderCache.highlightedHtml.put(activeCacheKey.value, html)
                                    }
                                }
                            }
                        }, "Android")

                        webViewClient = object : WebViewClient() {
                            @SuppressLint("ClickableViewAccessibility")
                            override fun onPageFinished(view: WebView?, url: String?) {
                                super.onPageFinished(view, url)
                            }
                        }
                        var startX = 0f
                        var startY = 0f

                        setOnTouchListener { view, event ->
                            when (event.action) {
                                android.view.MotionEvent.ACTION_DOWN -> {
                                    startX = event.x
                                    startY = event.y
                                    view.parent?.requestDisallowInterceptTouchEvent(true)
                                }
                                android.view.MotionEvent.ACTION_MOVE -> {
                                    val dx = Math.abs(event.x - startX)
                                    val dy = Math.abs(event.y - startY)
                                    if (dy > dx) {
                                        view.parent?.requestDisallowInterceptTouchEvent(false)
                                    } else {
                                        view.parent?.requestDisallowInterceptTouchEvent(true)
                                    }
                                }
                            }
                            false
                        }
                    }
                },
                update = { webView ->
                    if (webView.tag != html) {
                        webView.loadDataWithBaseURL(
                            "https://cdn.jsdelivr.net/",
                            html,
                            "text/html",
                            "UTF-8",
                            null
                        )
                        webView.tag = html
                    }
                },
                onRelease = { webView ->
                    // [Performance optimization]
                    // Called when an item leaves the screen and its Composable is destroyed in LazyColumn.
                    // Without explicitly calling destroy(), WebView native resources accumulate while waiting
                    // for GC, risking jank and OOM during long scrolling sessions.
                    webView.stopLoading()
                    webView.destroy()
                }
            )
        }
        Surface(
            modifier = Modifier
                .align(Alignment.TopEnd)
                .padding(4.dp),
            shape = RoundedCornerShape(16.dp),
            color = Color.Transparent
        ) {
            Row {
                IconButton(
                    onClick = {
                        val clipboard = context.getSystemService(android.content.Context.CLIPBOARD_SERVICE) as android.content.ClipboardManager
                        clipboard.setPrimaryClip(android.content.ClipData.newPlainText("code", normalizedCode))
                    }
                ) {
                    Icon(
                        imageVector = Icons.Outlined.ContentCopy,
                        contentDescription = stringResource(R.string.copy),
                        tint = colors.onSurfaceVariant,
                        modifier = Modifier.size(16.dp)
                    )
                }

                if (mermaid && mermaidError != null) {
                    IconButton(onClick = { showMermaidErrorDialog = true }) {
                        Icon(
                            imageVector = Icons.Outlined.ErrorOutline,
                            contentDescription = stringResource(R.string.mermaid_error_details),
                            tint = colors.onSurfaceVariant,
                            modifier = Modifier.size(16.dp)
                        )
                    }
                }
            }
        }
    }
    if (showMermaidErrorDialog && mermaidError != null) {
        val errorMessage = mermaidError.orEmpty()
        val onSurfaceVariantColor = colors.onSurfaceVariant
        val primaryColor = colors.primary
        val mermaidErrorSource = stringResource(R.string.mermaid_error_source, errorMessage, normalizedCode)

        AlertDialog(
            onDismissRequest = { showMermaidErrorDialog = false },
            title = { Text(stringResource(R.string.mermaid_error_title)) },
            text = {
                SelectionContainer {
                    Column {
                        Text(errorMessage)
                        HorizontalDivider(modifier = Modifier.padding(vertical = 12.dp))
                        Text(
                            text = code,
                            style = MaterialTheme.typography.bodySmall.copy(
                                fontFamily = FontFamily.Monospace,
                                color = onSurfaceVariantColor
                            )
                        )
                    }
                }
            },
            confirmButton = {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.End
                ) {
                    TextButton(
                        onClick = {
                            showMermaidErrorDialog = false
                            onAskAi(
                                mermaidErrorSource
                            )
                        }
                    ) {
                        Text(stringResource(R.string.ask_ai), color = primaryColor)
                    }
                    IconButton(
                        onClick = {
                            val clipboard = context.getSystemService(android.content.Context.CLIPBOARD_SERVICE) as android.content.ClipboardManager
                            clipboard.setPrimaryClip(
                                android.content.ClipData.newPlainText("mermaid-error", errorMessage)
                            )
                        }
                    ) {
                        Icon(
                            imageVector = Icons.Outlined.ContentCopy,
                            contentDescription = stringResource(R.string.copy),
                            tint = primaryColor
                        )
                    }
                    TextButton(onClick = { showMermaidErrorDialog = false }) {
                        Text(stringResource(R.string.confirm), color = primaryColor)
                    }
                }
            }
        )
    }
}

private val escapedLeadingSpaces = Regex("^(?:\\\\u0020)+")
private val malformedCompiledSpacePrefix = "\u0002" + "0"

internal fun normalizeResourceIndentation(code: String): String =
    code.lineSequence().joinToString("\n") { line ->
        val withoutMalformedPrefix = if (line.startsWith(malformedCompiledSpacePrefix)) {
            line.replaceRange(0, malformedCompiledSpacePrefix.length, " ")
        } else {
            line
        }
        val escapedIndent = escapedLeadingSpaces.find(withoutMalformedPrefix)
        if (escapedIndent == null) withoutMalformedPrefix
        else withoutMalformedPrefix.replaceRange(
            escapedIndent.range,
            " ".repeat(escapedIndent.value.length / "\\u0020".length)
        )
    }

// Language detection function
private fun detectLanguage(code: String): String {
    val trimmed = code.trim()
    return when {
        // Kotlin declarations, including examples such as: val name = "SmartSpend"
        Regex("(?m)^\\s*(val|var)\\s+[A-Za-z_]\\w*\\s*=").containsMatchIn(code) ||
            Regex("(?m)^\\s*((suspend\\s+)?fun|data\\s+class|sealed\\s+class|object)\\b").containsMatchIn(code) -> "kotlin"
        Regex("(?m)^\\s*def\\s+[A-Za-z_]\\w*\\s*\\(").containsMatchIn(code) ||
            Regex("(?m)^\\s*from\\s+\\S+\\s+import\\s+|^\\s*import\\s+[A-Za-z_]\\w*").containsMatchIn(code) -> "python"
        Regex("(?m)^\\s*(function|const|let|var)\\b").containsMatchIn(code) ||
            Regex("=>|console\\.log\\s*\\(").containsMatchIn(code) -> "javascript"
        Regex("(?m)^\\s*(public|private|protected)?\\s*(static\\s+)?(class|interface|enum)\\b").containsMatchIn(code) ||
            Regex("(?m)^\\s*public\\s+static\\s+void\\s+main\\s*\\(").containsMatchIn(code) -> "java"
        Regex("(?i)\\b(select|insert|update|delete)\\s+.+\\s+from\\b").containsMatchIn(code) -> "sql"
        Regex("(?is)^\\s*<!doctype\\s+html|<html(?:\\s|>)").containsMatchIn(code) -> "html"
        (trimmed.startsWith("{") && trimmed.endsWith("}")) ||
            (trimmed.startsWith("[") && trimmed.endsWith("]")) -> "json"
        else -> "plaintext"
    }
}

// HTML escaping function
private fun escapeHtml(text: String): String {
    return text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")
        .replace("'", "&#x27;")
        .replace("/", "&#x2F;")
}
